### PR TITLE
Add zola

### PR DESCRIPTION
**Pull request by Keats**
Add zola as a replacement for gutenberg for versions equal or above 0.4.3

See https://github.com/Keats/gutenberg/issues/377 for the discussion about the new name. The repo hasn't been moved yet as I want to minimize disruption with netlify if possible.

### CODE REVIEW

**Comment by Keats** [comment]
CI failure seems unrelated?

**Comment by Keats** [comment]
Ping @calavera , I can do the PR to update the binrc version in https://github.com/netlify/build-image afterwards

I can also have a look at the CI failure if that would be blocking a release

**Comment by VitalyAnkh** [comment]
I like "Zola". Why not merge right now?

**Comment by rybit** [comment]
The main reason to not merge right now is because the build is failing on go 1.8 and 1.9.

**Comment by Keats** [comment]
The issue is from the Makefile as it is go get-ting the statik package and gets its `master` which doesn't work in Go < 1.10 right now as the `Modified` field from https://github.com/rakyll/statik/blob/master/statik.go#L163 was introduced in Go 1.10. As far as I can see, no one can currently build `binrc` with go 1.8/1.9 so I would suggest changing the target to at least 1.10 since I don't think `dep` can install binaries.

I do get a different compilation error on master with go 1.11 though but that's an easy fix.

**Comment by Keats** [comment]
I made a PR to statik (https://github.com/rakyll/statik/pull/54) to make it compatible with Go < 1.10 again in the meantime

**Comment by Keats** [comment]
@rybit would it be ok to point https://github.com/netlify/binrc/blob/master/Makefile#L14 to my fixed fork or better, to a fork from Netlify of my fork so the build works and doesn't break again?

**Comment by rybit** [comment]
Sorry -- I'd like point to the primary repo, I'd say fork this and have it point until they merge your PR

**Comment by Keats** [comment]
Done, I'll do another PR to switch back the original statik once my PR is merged

**Comment by Keats** [comment]
@rybit anything else I need to do?

**Comment by Keats** [comment]
@calavera @rybit ping, I'm kinda hoping to have zola work immediately since many current gutenberg users (including me) are using netlify

**Comment by Keats** [comment]
My PR for statik got merged but now it looks like some Go dependencies removed support for 1.8: https://github.com/golang/go/issues/28291

One day a Go project will build successfully, one day.

**Comment by calavera** [comment]
we should update our Go version dependency. We're not using those old versions anymore. Merging this for now. Thanks @Keats
